package com.povush.modusvivendi.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF642424)
val onPrimaryLight = Color(0xFFFFFF99)
val primaryContainerLight = Color(0xFFEEECE1)
//val onPrimaryContainerLight = Color(0xFF3B080B)
val secondaryLight = Color(0xFF773434)
val onSecondaryLight = Color(0xFFFFFFB2)
val secondaryContainerLight = Color(0xFFF4ECDC)
//val onSecondaryContainerLight = Color(0xFF2C1514)
//val tertiaryLight = Color(0xFF735A2E)
//val onTertiaryLight = Color(0xFFFFFFFF)
//val tertiaryContainerLight = Color(0xFFFFDEAA)
//val onTertiaryContainerLight = Color(0xFF271900)
//val errorLight = Color(0xFFBA1A1A)
//val onErrorLight = Color(0xFFFFFFFF)
//val errorContainerLight = Color(0xFFFFDAD6)
//val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF1B1717)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1B1717)
val surfaceVariantLight = Color.Transparent
val onSurfaceVariantLight = Color(0xFF1B1717)
//val outlineLight = Color(0xFF857372)
//val outlineVariantLight = Color(0xFFD7C1C0)
//val scrimLight = Color(0xFF000000)
//val inverseSurfaceLight = Color(0xFF382E2D)
//val inverseOnSurfaceLight = Color(0xFFFFEDEB)
//val inversePrimaryLight = Color(0xFFFFB3B0)
//val surfaceDimLight = Color(0xFFE8D6D5)
//val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFF332640)
val surfaceContainerLowLight = Color(0xFF403152)
//val surfaceContainerLight = Color(0xFFFCEAE8)
//val surfaceContainerHighLight = Color(0xFFF6E4E3)
//val surfaceContainerHighestLight = Color(0xFFF0DEDD)